Modified sanctions
antonypap/SOMAS2022 pull request #14
Opened 2023-02-01 02:40 UTC by antonypap

2023-02-02 09:00 UTC, MattSScott approved these changes
Pretty sure we've fixed this now!

2023-02-02 15:10 UTC, MattSScott commented
Great stuff - well done guys

2023-02-02 15:46 UTC, MattSScott approved these changes
Good to merge imo

2023-02-02 15:46 UTC, MattSScott commented on pkg/infra/teams/team3/leader_strat.go
> +	return prunned
Bit annoying, but can we change 'prunned' to 'pruned'

2023-02-04 13:12 UTC, MattSScott requested changes
Some cleaning to do. Can we also review my contribution to refactoring? I can't comment on this objectively

2023-02-04 13:12 UTC, MattSScott commented on pkg/infra/teams/team3/election_strat.go
> +					break
This, and `itr3` perform basically the same functionality, just with different arguments. I would package this into a function

2023-02-04 16:28 UTC, antonypap commented
Refactor LGTM

2023-02-04 18:21 UTC, MattSScott commented
Lovely

2023-02-06 11:38 UTC, merged